config/routes.rb
Utopia::Application.routes.draw do
 
resource  :post

resource  :comments
	
 match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
 match 'auth/failure', to: redirect('/'), via: [:get, :post]
 match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

root :to => 'posts#index'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comment
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private
	  def current_user
	    @current_user ||= User.find(session[:user_id]) if session[:user_id]
	  end

  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
	#retrive all post from the datbase so that they can be displayed
	@post
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Utopia</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="user-widget">
	  <% if current_user %>
	    Welcome <strong><%= current_user.name %></strong>!
	    <%= link_to "Sign out", signout_path, id: "sign_out" %>
	  <% else %>
	    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
	  <% end %>
	</div>
	<br/>
	<%= yield %>
	
</body>
</html>

app/views/posts/index.html.erb
<h1>Posts#index</h1>